### ISSUE TITLE
Feature request: Adding a new widget should open the controls for that widget immediately

### ISSUE THREAD

**Issue by richardtape** [siteorigin/siteorigin-panels#142]
Right now when you add a widget to the editor you then have to click the edit button to set the properties for it. I know, right? A whole extra click. Facetiousness aside, if you have many widgets in the editor it can be a little awkward for the user to grok exactly which widget they've just added. It'd be nice to add the widget and immediately open the editing screen for it.

Thoughts?

**Comment by gregpriday** [comment]
As far as I remember, this is how we used to do it before the version 2.0 update. Perhaps readding it as an optional setting for users who prefer it is a good idea though.

It was a gut feel that it might feel a bit jarring having the widget window open up right away. Also, because of the nice widget navigation we added (the option to go left/right through widgets on a page), it felt more natural to let a user quickly setup their page and widgets first, then go through and add their content. Again, just a gut feel.

**Comment by richardtape** [comment]
Thanks for replying @gregpriday 

Interesting. Even if the feature was still there but behind a filter, I could get behind that. Decisions, not options. (But with a bit of flexibility should you want it... :) )

I'm happy to see if I can re-add this if you could point me to something in the history about where this was implemented?

**Comment by jambox** [comment]
Agree with @richardtape here
