### ISSUE TITLE
Large performance hit on mobile devices when Virtue theme is active

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#172]
[Issue reported in this thread](https://siteorigin.com/thread/page-builder-scroll-issue/)

When the user is using the [Virtue](https://wordpress.org/themes/virtue/) theme (70k active) with a standard prebuilt layout on the page there seems to be a large amount of "lag" on the page. I'm able to replicate this locally but I haven't been able to spot the issue myself so it's quite possible this is more of a theme issue, however, this should be looked into regardless due to a potential performance increase if it's on our end.

**Comment by gregpriday** [comment]
There is a chance that this is an issue with Parallax. We've had reports that the parallax library we're using has some performance issues because of the way it uses background images. I've created an issue for handling this change - https://github.com/siteorigin/siteorigin-panels/issues/173

For now, I'm going to close this thread unless we're able to figure out what the specific issue is. It's more than likely the parallax performance issue though.
