### ISSUE TITLE
Negative margin on full width rows causing horizontal scroll on themes without padding to prevent this

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#174]
[Issue reported in this thread](https://siteorigin.com/thread/horizontal-scroll-bug/), although it has come up before. Can be replicated in any theme without extra side padding, for example [_s](http://underscores.me/) with default settings. Greg suggested overflow could be used to potentially prevent this.

The issue is basically explained in the title of this issue.

**Comment by gregpriday** [comment]
The only problem with overflow (which has since come up in testing) is that widgets that are designed to overflow, have their content hidden. One example is a widget that generates a modal. Negative margins are here for the time being, so I'd consider this one of the main aspects of a theme making itself Page Builder Compatible.

**Comment by gregpriday** [comment]
At some point we can look at making Page Builder work without negative margins. This might be possible now with flex layouts. The main issue has always been that leaving out the negative margin causes cells to not align properly.

**Comment by AlexGStapleton** [comment]
This is resolved as of 2.5 due to the new flex based layout, or do you still think it's worth fixing this for the legacy renderer?

**Comment by Misplon** [comment]
Let's not fix and defer to the flex based layout to resolve.
