### ISSUE TITLE
widgets seem to be processed twice (or as many times as it's called) when the_excerpt() is called

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#180]
Whenever the_excerpt() is called the page builder seems to process the page multiple times - dependent on how many times the function is called. This issue causes issues with [forms (Contact Widget)](https://github.com/siteorigin/so-widgets-bundle/issues/122), and [sometimes shortcodes](https://siteorigin.com/thread/hero-widget-doesnt-accept-shortcode-ultimate/). 

To replicate this without any third party plugins simply add the following code to your functions.php:

```
function show_contact_error(){
    $excerpt = get_the_excerpt();
}
add_action( 'template_redirect', 'show_contact_error' );
```

**Comment by braamgenis** [comment]
After looking into this a bit more, I don't think this should be considered a bug. The WordPress core applies the `the_content` filter when `get_the_excerpt` is called, which is expected and correct behaviour. This should really be handled by the Contact Form widget, or any other widgets for which this behaviour causes issues.

**Comment by AlexGStapleton** [comment]
Ah okay. I had a brief look at the soruce of get_the_excerpt() and muist have missed that - doh!

So yeah, you're right this isn't directly a bug as it's intended however it might be a good idea to put in a fail safe for those not aware of it.

**Comment by egemenerd** [comment]
Hi guys,

I'm a theme author and I used SiteOrigin page builder in most of my themes. I think it is the best free page builder plugin. Thank you very much for making this plugin!

I'm working on a blog theme now and I made a lot of widget using the SiteOrigin Widgets Bundle as a framework, but there is really a big problem here which is related to the live editor. The_excerpt function makes live editor crash. I tried some other plugins and they are all not working. For example, Livemesh SiteOrigin Widgets plugin. Post carousel widget in this plugin is not working on the live editor too because he has used get_the_excerpt function...

If it is impossible to make this function work, is it possible to disable it on the live editor?

I tried https://codex.wordpress.org/Function_Reference/is_admin but it doesn't work. Is there any other conditional tag or any filter to do that? 

I appreciate any help you can provide...

Thanks in advance!

**Comment by AlexGStapleton** [comment]
Hi egemenerd,

Thank you for the kind words! 😃

Could you please make a new issue? The issue you're experiencing is different to this issue as this one relates to widget output and your issue relates to the live editor.

Regardless, I'm able to use the_excerpt() and get_the_excerpt() and still use the Live Editor without issue. Could you please elaborate on exactly why you think it's related to get_the_excerpt()? Please include a response to this in the new issue rather than a direct comment here.
