### ISSUE TITLE
Live Editor should use breakpoints defined in PB settings for tablet and mobile views.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#211]
The live editor should use breakpoints defined in the PB settings for tablet and mobile views. This way the user can adjust them if their theme has different breakpoints and it'll overall produce a more consistent preview with the what the user will see..

**Comment by gregpriday** [comment]
The 2 values actually represent slightly different things.

The mobile width setting isn't really the value that decides when the most common mobile width is, but when the mobile view should start. So the upper end.

This means the preview would be showing the user an upper end of range, rather than the most common mobile width.

**Comment by AlexGStapleton** [comment]
Ah. In hindsight, that's quite obvious. :(

**Comment by gregpriday** [comment]
We can look at having a way to customize the display with the 2.6 update. That's when we'll be putting more work into the Live Editor.
