### ISSUE TITLE
Issue with custom fields

### ISSUE THREAD

**Issue by fakeartist** [siteorigin/siteorigin-panels#213]
Hi. I have the following bug. I have a custom field (WYSWIG) to a page. When I use the panel editor on the page's default editor, then for some reason, when I try to get the custom field's content, it returns the content of the panel editor. Tested both with Types and Custom Field Suite.

**Comment by fakeartist** [comment]
One clarification .The bug only comes up with WYSWIG custom fields. For other field types (eg. textarea), it works fine.

**Comment by braamgenis** [comment]
Hi @fakeartist We would need more information about your custom field to be able to investigate this further. Is it something you coded yourself or from a plugin like Advanced Custom Fields?

**Comment by fakeartist** [comment]
The the bug appears when I use Custom Field Suite plugin or Types plugin.

**Comment by braamgenis** [comment]
@fakeartist Ah, sorry. I missed that from your first post. Thanks for the info! So can you elaborate on how exactly you're trying to "get the custom field's content"? Can you give a code example? I see that Custom Field Suite uses the TinyMCE editor for it's WYSIWYG field. Page Builder uses the default editor to save it's content, and it's possible it's confusing the two editors or saving it's content in both due to naming conflicts.

**Comment by fakeartist** [comment]
Sure. In Custom Field Suite, I use the usual plugin's command

```
$my_custom_field = CFS()->get('my_custom_field');
echo $my_custom_field
```

This should echo the custom field's value. Instead, it echoes the content of the of the panel editor.

**Comment by braamgenis** [comment]
Thanks for that. I'll look into this soon.
