### ISSUE TITLE
Divs are removed when "Revert to Editor" is used

### ISSUE THREAD

**Issue by maarcin** [siteorigin/siteorigin-panels#223]
Hi guys,

not sure if this is on TODO list, but I wanted to put it here for future reference.

Topic about the issue is available <a href="https://siteorigin.com/thread/removed-div-from-widget/">here</a>.

Basically after switching to default editor with `Revert to Editor` button Page Builder removes all divs from widgets.

The code that causes the issue is this one (in siteorigin-panels.js):

> t.find( 'div' ).each( function () {
var c = $( this ).contents();
$( this ).replaceWith( c );
} );

Maybe adding check for Page Builder specific class would solve the issue here instead of using just `div`? I tried simple solution (just for testing) and wrapped this code with hasClass and it worked for me, but of course you may find better solution.

I talked about this with Andrew and he told me that you'll relook at this when you'll find some time.

Thanks for your time guys :)

Cheers

**Comment by gregpriday** [comment]
Thanks for the feedback @maarcin!

This was actually intentional. We wanted to keep the content in `post_content` as text-only as possible. This feature's primary purpose was so that pages built with Page Builder still come up in your WordPress search, SEO plugins and other search plugins.

In all these cases, the extra `div` tags are just a waste of space.
