### ISSUE TITLE
Large performance hit when over 50k charecters

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#231]
Create a WordPress page and input 50,000 characters. You'll notice very little performance impact of this outside of maybe the initial paste. Convert the page into a Page Builder page and there will be a massive performance impact that should be instantly visible by scrolling. Save the page and the page builder will quite a while to display.

[Example layout](https://u.teknik.io/tmBfv.json)

**Comment by gregpriday** [comment]
One possible cause is the request to the server that updates the visual editor content. We originally added this for compatibility with things like Yoast SEO, but perhaps we should put an upper limit on the amount of content that'll be processed.

**Comment by gregpriday** [comment]
Testing this out now, this issue goes a little deeper than I originally thought. So it turns out it's a conflict with the `adjust` function in `wp-admin/js/editor-expand.js`. This function seems to handle the toolbar pinning. It triggers on a scroll event, which is why we're seeing scrolling performance issues.

For some reason, when the editor is hidden and Page Builder is being displayed, this `adjust` function is a lot heavier.

We need to find a way to trick the main editor into not calling `adjust` when Page Builder is in use. A simple way would be to use:

```
if( window.wp.editor ) {
    window.wp.editor.fullscreen = true;
}
```

This tricks the WordPress editor into thinking it's in full-screen mode. That causes a few other problems though, so we'd just need to be smart about how we add this.

Another option would be to limit the amount of content in the Visual Editor when using Page Builder. This might involve cropping out some of the user's content though.

For now, we'll just suggest that users with large pages disable copy content, and build their pages in Page Builder from scratch.

**Comment by gregpriday** [comment]
I just double checked and this issue is still coming up. I'm lowering the priority because it is a slight edge case. Maybe there's something we can do to fix it though.
