### ISSUE TITLE
UX: Add ability to label rows / widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#232]
The ability to label rows and widgets should be implemented for easier referencing. Right now, layouts like the one seen below provide little information at a glance. This can add significant development time for people unfamiliar with a layout or for when layouts are really complicated. This is especially true when multi-column layout builder widgets are present.
 ![](https://i.imgur.com/pZRHxJF.png)

**Comment by AlexGStapleton** [comment]
[This is a really good use case for this.](https://siteorigin.com/thread/another-vote-for-being-able-to-annotate-rows-and-widgets/#comment-95373)

For reference, 

> Clients were editing the row that only displays on desktop when they should have been editing the row that displays on mobile. They never look at the Attributes box and they forget to look at my instructions in the Peters Post Notes box over on the side.

**Comment by LuBevilacqua** [comment]
Hello,
while waiting for the much appreciated ability to name rows and widget, I would like to suggest a quick fix for the widget description, as I wrote [here](https://siteorigin.com/thread/how-can-i-control-the-widget-description-in-a-pagebuilder-grid/).
Right now widget data can contain panels_title, but it seems used just to explicitly force default widget description (if set to false). I would suggest to use it also to refer to a specific field of the widget itself, so that the widget developer can choose which field to use as description.
This is helpful, for example, for the actual Headline widget: the code of the function getTitle (from siteorigin-panels-xx.js) checks for first-level fields, not fields inside a section. Headline title is defined into a section, and this translates to a generic unhelpful widget description "A headline widget".
Hope this could help!
Thank you for the great work so far.
Luigi

**Comment by gregpriday** [comment]
Yeah, this could be a really good addition.

**Comment by gregpriday** [comment]
@braamgenis have actually chatted about this. We're going to go with the ability to set widget titles rather than row titles. So changing the text "SiteOrigin Hero", so something more custom. This means we're just giving users the ability to modify something that's already there, rather than trying to figure out a way to fit in row labels.

We also almost have a feature ready where you can color code rows, which will go a long way to making things readable without adding clutter.

**Comment by braamgenis** [comment]
Implemented in #371
