### ISSUE TITLE
Content issue when use "Revert to Editor" and revert back content text mode to Page builder 

### ISSUE THREAD

**Issue by rvpatel** [siteorigin/siteorigin-panels#252]
- Not  Any extra plugin activated now.
- using wordpress  4.5.3 with twenty sixteen theme for test
- Page Builder by SiteOrigin Version 2.4.9 
 -SiteOrigin Widgets Bundle Version Version 1.6.1

Steps :
1) Added search form on content.
http://awesomescreenshot.com/0fa5zq9a27

2) Click on "Revert to Editor" content display in text mode.
http://awesomescreenshot.com/0715zq9h1f

3) All content added on "Site Origin Editor" and we lost format when revert back order content to Page builder

http://awesomescreenshot.com/0395zq9m41

**Comment by AlexGStapleton** [comment]
Oh. I just responded to your thread on [WordPress.org](https://wordpress.org/support/topic/page-builder-content-lost-when-back-content-text-mode-to-page-builder?replies=2#post-8592790).

To summarise my previous reply, this isn't an issue (it's by design) and it's not really something we can fix. :(

Thanks for reporting the feedback regardless.
