### ISSUE TITLE
Live editor focusing wrong elements

### ISSUE THREAD

**Issue by slifin** [siteorigin/siteorigin-panels#26]
It seems to be focusing the element after the one currently hovered over, I'd be interested to know if this issue can be replicated on other people's installs or whether it's something about my page causing the problem

![hover problem](https://cloud.githubusercontent.com/assets/198857/6024614/50c2ee48-abc4-11e4-8c36-652bf99553be.gif)

**Comment by gregpriday** [comment]
It would be very useful. Could you send it to greg@siteorigin.com

**Comment by slifin** [comment]
Did you get in okay?

**Comment by gregpriday** [comment]
So from the looks of things, the Grid widget you've added to this page isn't properly outputting the before_widget and after_widget arguments. Not having this content is throwing off the live editor because it's not identifying the Grid widget as a widget.

Most widgets do echo out these arguments as recommended by the WordPress docs - http://codex.wordpress.org/Widgets_API

Do you know where you got this widget from so I can report this to them?

**Comment by slifin** [comment]
haha embarrassing, I am the author
thank you for taking a look I'll fix this and double check my other widgets for this asap
