### ISSUE TITLE
2.5 beta2 colapse order

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#375]
Hi,
Overall I like the 2.5 version. I also salute you for moving everything to FlexBox. 
Great work.

However, the changes you made on collapse order row behaviour breaks all our theme demos,  without the possibility to rebuild it back to the way it was with current options.

**How it worked before:** 
- When "Collapse Order" was set on "right on Top", the items collapsed on tablet view and also on mobile view.

**How it works now:**
The Collapse Order doesn't work until you check "Collapse On Mobile" and it only sets the order on mobile, not tablets.

**implications of this changes for us**
We sell premium themes and most of the clients import the demo content. If Collapse Order stays as it is in beta version, all clients sites will break upon update of the PageBuilder. 

For us this means a very wild couple of weeks with a lot of support tickets and quite possible negative item ratings.

**Suggestion for changes: **

For the backward compatibility, I would suggest the following changes:

Collapse option should not be a checkbox, but a select with the following options:
- Collapse on Tablets and Mobile (default option)
- Collapse on Mobile
- Do not Collapse

I really hope you consider this, to ensure backward compatibility.

**Comment by gregpriday** [comment]
Keeping themes that integrate with Page Builder happy, is one of our top priorities, so we'll definitely look at this.

So you have any demo content/layouts that I can use to test?

**Comment by andrejarh** [comment]
Hi Greg,
I will set up a demo site for you and send you login data.

**Comment by gregpriday** [comment]
Perfect. You can just sent them to greg@siteorigin.com

**Comment by andrejarh** [comment]
Done.

**Comment by gregpriday** [comment]
We've managed to sort out this issue. We'll be sending out another beta release on Monday with this and a few more fixes.

With the *Collapse On Mobile* setting. Are you seeing that as disabled by default? This setting should always be enabled by default, even for existing pages. I've tested this with existing pages created using the 2.4.x branch and it seems to be defaulting to `true` for me.

Maybe there's something I'm missing. Or could there be some custom code in your themes that might be interfering with these defaults? Either way, I'm happy to investigate.

**Comment by andrejarh** [comment]
Thank you Greg, will definitely test the new version. Did you receive my email?
I've also sent you another issue. Some of our extended code stopped working. Like this one: https://gist.github.com/andrejarh/f84e27db3f7cee1975a61f3c1b0d562a
(background color opacity)

**Comment by gregpriday** [comment]
We've moved the styling out of inline `style="..."` attributes and into the general CSS that Page Builder generates. So that filter you're using won't work. Ideally, this should be filtered earlier.

I'll look at your use case and see what filters we'd need to have to let you filter that earlier. It's already possible by filtering `siteorigin_panels_data`, but I'll look at making filters that are more focused on filtering style values.

**Comment by gregpriday** [comment]
I've added a filter for the layout_data array, which is a nicely formatted array that contains the style values.

https://github.com/siteorigin/siteorigin-panels/commit/a3a05d19449d406694cb7d424966502234f39e36

Having a look at your implementation of background color opacity, you should be able to just change the value for the background color in this array based on the style value from your theme. This is a far more robust way of filtering, because even if we change the output format in the future, it won't change how your filter works.

**Comment by andrejarh** [comment]
Thank You Greg.
I will look into this and modify our code. 
I noticed a lot of features just work better in beta 3. 

I can't thank you enough.

**Comment by gregpriday** [comment]
Very glad to hear it! Yeah, we managed to fix a lot of issues between beta 2 and beta 3. I'm fixing a few more today, so this should be a very smooth, stable release.
