### ISSUE TITLE
Row: going from Left to Right.

### ISSUE THREAD

**Issue by Paul-Allen** [siteorigin/siteorigin-panels#379]
I was hoping the Left to Right feature would work on this new release.

If you change Left to Right to Right to Left and then click Set, nothing happens, it stays on Left to Right even after updating the page.

However, the responsiveness for that particular page no longer works. Each panel no longer goes 100% width on smaller screens.

**Comment by gregpriday** [comment]
Thanks for reporting this @Paul-Allen - I'll take a look before the release goes out.

**Comment by gregpriday** [comment]
So the first issue for adjusting the row left and right - this is actually just a UI issue. Because the layouts in Page Builder are completely flexible, what you have set at the top of the screen, doesn't actually represent the structure of your row. It's a tool, that allows you to set a row layout that you can then adjust.

So the task there is to change how the row dialog is displayed to make it clear that block is a tool, rather than an indicator. It's more a set of predefined row layouts that you can load.

For the responsiveness issue. This might be a cache issue. Can you try [clearing](http://www.refreshyourcache.com/en/home/) your browser cache and see if that fixes the issue? If not, would it be possible for you to create a public URL where I can see the issue in action?

**Comment by Paul-Allen** [comment]
No problem Greg.

The responsive issue is definitely not cache related.

The responsiveness was working fine on a site I'm testing on. When I set the row to Right to Left then click update the responsive issue appears.

If I go to another page there is no problem with responsiveness.

If I then make the Right to Left change on this page then the responsive issue appears again.

I'll create a public demo and email you the details if that's ok?

**Comment by gregpriday** [comment]
Great. I'll log in and take a look.

**Comment by Paul-Allen** [comment]
Most strange, I can't seem to recreate the issue on a public URL.

I have identical set up to the local version and the issue does not exist.

What I've noticed on the local site now is when I change Right to Left it disables Collapse on Mobile in the layout settings.

If I now enable this all is working as expected.

If I now change Right to Left again the responsiveness works as expected.

Very strange.

**Comment by Misplon** [comment]
Hi @Paul-Allen. Are you still experiencing any problems with this feature? Thanks.
