### ISSUE TITLE
High number of post queries 

### ISSUE THREAD

**Issue by LittleHamster** [siteorigin/siteorigin-panels#391]
I just saw [this review](https://wordpress.org/support/topic/poor-coding-standards/) and also I don't appreciate when people leave bad reviews for not being able to use a plugin, I got concerned when I got similar results. 

### Issue: 
When using [Query Monitor](https://en-ca.wordpress.org/plugins/query-monitor/) the number of post queries by SiteOrigin is very very high. In the review the person got 144 queries. 

I just installed Query Monitor on my local host and tested it on a page which uses pagebuilder and I got **76 queries** by page builder: 

<img width="740" alt="screen shot 2017-04-17 at 12 43 34 am" src="https://cloud.githubusercontent.com/assets/10330481/25079051/f70fef1a-2306-11e7-8e52-96552b0325aa.png">

In that page I only used 2 Post Loops widget. 

First time I am using Query Monitor so dont know how accurate it is, I just thought open up this issue to see if @gregpriday has time to investigate

**Comment by gregpriday** [comment]
I posted a reply to that review. Yeah, reporting issues like this is best done here on Github, rather than a 1 star review - but different people have different methods.

Page Builder lets you add any kind of widget you want to a page, but each widget is dynamically generated. So the widget is allowed to make any calls it likes and it seems like these calls are attributed to Page Builder by that plugin.

We could make the plugin baby a user and force them to only use certain widgets, but this would severly limit the power of Page Builder. I created a very large page using only SiteOrigin Editor widgets. This widget doesn't make any database calls.

As expected, I only had 4 database queries, which is for things like getting post meta and getting options.

<img width="713" alt="screen shot 2017-04-17 at 7 11 58 am" src="https://cloud.githubusercontent.com/assets/1126859/25079521/8593ec10-233d-11e7-8e10-be423e7c7a9c.png">

If you absolutely need both performance and additional widgets, then you can install a caching plugin.

**Comment by AlexGStapleton** [comment]
@LittleHamster What is the page you're testing? I ask as I got similar results to Greg and all of the queries make sense.

![](https://i.imgur.com/i3wyMqG.png)

Those 4 queries are the standard queries run when you load a page. To be honest, I'm unsure why they're directly associated with SiteOrigin Page Builder as they're most definitely not.

**Comment by LittleHamster** [comment]
@gregpriday thanks for the quick investigation. I got similar results when using the SiteOrigin Editor.  But as soon I put some Post Loop widgets then the number increases,

@AlexGStapleton the page I tested which returned 76 queries has the following widgets:
-  5 Post Loop Widgets
- 4 SiteOrigin Editor Widgets
- 3 SiteOrigin Headline widgets

and here are the number of posts returned for each post loop: 
- Post loop #1, #2   : returns 1 post
- Post loop #3, #4  : returns 5 posts
- Post loop #5         : returns 3 posts

it also shows that I have 15 duplicate queries all by `Plugin: siteorigin-panels`

thanks again guys for the quick response 👍

**Comment by LittleHamster** [comment]
I just did some more testings and using visual composer I created two post loops and each returned 10 posts (20 posts in total) and here are the query results: 

<img width="827" alt="screen shot 2017-04-17 at 2 00 20 am" src="https://cloud.githubusercontent.com/assets/10330481/25080400/cf02bac4-2311-11e7-8470-3f9f3cf1622e.png">

I created two post loops widget using PageBuilder with 10 posts each (20 in total) and here are the query results: 

<img width="793" alt="screen shot 2017-04-17 at 2 03 33 am" src="https://cloud.githubusercontent.com/assets/10330481/25080452/2e0a430c-2312-11e7-9f55-6e9f15278a3b.png">

**Comment by AlexGStapleton** [comment]
Would it be possible for you to send me an export of your test page? To do this open up the page with the widget and click layout in the Page Builder toolbar. Then click import/export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://upload.teknik.io/">teknik.io</a>.

Please note that Visual Composer handles things in a much different manner and can't really be compared.

**Comment by LittleHamster** [comment]
@AlexGStapleton sure, 
here is the [json output](https://u.teknik.io/rszwC.json)
and here is the [loop template](https://raw.githubusercontent.com/Automattic/_s/master/template-parts/content.php) used in the Post Loop widget

**Comment by rohitmanglik** [comment]
Hi Team,

Thanks for debugging into the issue. I was not aware of your GitHub Support. I will definitely update the rating.

I can understand that you it's tough to reproduce the issue. Probably because of old site or high content I can getting that many queries. I have a production parallel environment whose credentials I can provide for debugging if that helps. Let me know where to send the details.

Thanks

**Comment by gregpriday** [comment]
Thanks, @rohitmanglik - an updated rating would mean a lot. We're not that active on WordPress.org because it's difficult for our team to collaborate effectively there, like we're able to do on our own forums and on Github.

If you send credentials to support@siteorigin.com, either @AlexGStapleton or I will take a look.

**Comment by AlexGStapleton** [comment]
@LittleHamster Hm. Let's try testing a basic page instead of as the post loop as when using the_content() it'll process the data for every post in the loop. In other words, the high query count makes sense as _every_ one of those pages is being loaded. This isn't a normal situation as normally users would use the_excrept() instead.

[Try giving this layout a try](https://u.teknik.io/UaKD1.json). I just want to confirm we have similar query count for basic pages. Please ensure you're using as few unrelated plugins as possible.

**Comment by rohitmanglik** [comment]
Hi,

I sent the credentials just now and updated the review.

@gregpriday and @AlexGStapleton can you please confirm and help me with next steps.

**Comment by AlexGStapleton** [comment]
@rohitmanglik Did you receive my reply? For reference, it was:

Oddly, I'm getting a 502 Bad Gateway error when trying to log in via /login/
Is there an alternative link I can use to log in with?

Based on your the linked page, I suspect the high query count may come down to the shortcodes and widgets being added by SiteOrigin Page Builder. Basically, I think they're being wrong attributed to SiteOrigin Page Builder. I'll be able to confirm then once I've taken a look at the plugin.

**Comment by rohitmanglik** [comment]
@AlexGStapleton I am sorry for delay. Yes, I received your reply.

The staging server I gave you was not updated in last 2-3 months so it gained some issues. I ran command to replicate the production server. It will take around 5 hours before it starts working again (size of my website is 60GB).

Once it's ready, I will let you know.

Thanks for your patience and looking into the issue in priority.

**Comment by AlexGStapleton** [comment]
Sorry for the delayed reply.

After running extensive tests on @rohitmanglik I've found as we're the interface/method that's being used to add widgets and shortcodes to the pages, we're being incorrectly being attributed with the resulting queries. An example of this is this screenshot which are the largest queries of all of the queries present on @rohitmanglik's home page:

![](https://i.imgur.com/mdiFzE3.png)


As you can see, the first query is related to rev slider, the second and last query are related to the post indexer plugin. They should be labeled under their respective plugins but due to SiteOrigin Page Builder being the method of adding them to the page (although I'm unsure how Post Indexer is being added - that may just be processing the resulting data), we're being incorrectly attributed.

What more, the other two generic queries (237 and 183) aren't SiteOrigin Page Builder either.
The first query is for a plugin called Sabai

![](https://i.imgur.com/xTC7MEB.png)

The second is for Rev Slider.
![](https://i.imgur.com/dtxXdYb.png)

After this I disabled all plugins but SiteOrigin Page Builder and the SiteOrigin Widgets Bundle. This allowed the query count to go from:

![](https://i.imgur.com/tSTEsCW.png)

To:

![](https://i.imgur.com/0S6QjTl.png)

After changing to a default theme (read: twenty Seventeen):

![](https://i.imgur.com/b9we1GS.png)
(I suspect the very large query time is due to the recently changed theme - I should have reloaded the page a few times :().

After updating to SiteOrign Page Builder 2.5.2:
![](https://i.imgur.com/GpFPyel.png)

After enabling the new page cache setting (WP Admin > Settings > Page Page Builder, open Content tab, tick Content Cache):

![](https://i.imgur.com/mpVZSvD.png)

(this setting will have a more noticeable effect when all of the other plugins are activated. It be deemed excessive with so few plugins/widgets activate at this point) 

Okay so in summary, I feel while 28 queries isn't the lowest in the world we've made significant overall performance increases regardless of this fact.

@rohitmanglik, are you happy with the resulting tests? Do you feel this is still a major concern?

**Comment by rohitmanglik** [comment]
Hi @gregpriday,

Thanks a lot for the analysis. This makes sense. Probably you can contact Query Monitor to make a few SiteOrigin related changes. It will also help us in finding out which plugin is consuming major chunk of our resources.

I already updated review in Wordpress Forums. Thanks for your support.
