### ISSUE TITLE
Cell vertical alignment - Stretched bug in Safari

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#399]
Stretched vertical alignment doesn't seem to work as it should on Safari.
here is example from Chome:
<img width="691" alt="screen shot 2017-04-26 at 14 58 54" src="https://cloud.githubusercontent.com/assets/10053621/25435669/1a7def74-2a91-11e7-8dc6-683866558855.png">

And here from Safari:
![screen shot 2017-04-26 at 14 58 21](https://cloud.githubusercontent.com/assets/10053621/25435678/25bb8dd8-2a91-11e7-891b-f6b1451c9496.png)

**Comment by AlexGStapleton** [comment]
Do you have a public URL where we can take a look at that page for reference?

**Comment by andrejarh** [comment]
Yes, of course. 
You can check it here: http://recycle.orionthemes.com/new-demo-1/home-2/

**Comment by AlexGStapleton** [comment]
Ah, I knew that face was familiar. Really like the look of that theme by the way. 👍 

Would it be possible for you to send me an export for this page? To do this open up the page with the widget and click layout in the Page Builder toolbar. Then click import/export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://upload.teknik.io/">teknik.io</a>.

**Comment by andrejarh** [comment]
Thank you Alex. 
What is your email address? I've set up a demo, and want to create an account for you to check.

I am not sure if exporting the layout would help much, as we have custom widgets and options in the theme. But you can try anyway if you wish. Here is the json file: [downloads.orionthemes.com/share/layout-27042017.json](http://downloads.orionthemes.com/share/layout-27042017.json)

Kind regards,
Andrej

**Comment by AlexGStapleton** [comment]
Ah, yeah that make sense. Please use support@siteorigin.com.

**Comment by andrejarh** [comment]
Done, credentials should already be on your mail. 
Thanks!

**Comment by hmjones** [comment]
Hey Guys. Was this ever resolved? I'm experiencing the same issue in Safari.

**Comment by gregpriday** [comment]
Safari must have fixed this issue, because it seems to be displaying properly now. I'm testing in 11.1. Always best that this gets fixed by the browser, rather than relying on CSS/JS hacks.

<img width="1466" alt="screen shot 2018-06-11 at 12 19 23" src="https://user-images.githubusercontent.com/1126859/41226425-b8cc168c-6d71-11e8-8b90-9591013b30e1.png">

I also checked with a local layout I created and everything seems to be working as expected. Going to close this, but anyone feel free to comment and I'll reopen.
