### ISSUE TITLE
Layout Builder: Doesn't currently use siteorigin_panels_builder_supports filter

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#433]
The layout builder doesn't currently support [siteorigin_panels_builder_supports](https://github.com/siteorigin/siteorigin-panels/blob/develop/tpl/metabox-panels.php#L5) filter. This is problematic as this filter is used to disable [certain page builder functionality](https://github.com/siteorigin/siteorigin-panels/blob/develop/js/siteorigin-panels/view/builder.js#L44). To bypass the disabled functionality in the non-widgetized version of Page Builder, they simply need to add a layout builder.

**Comment by gregpriday** [comment]
This is intentional, but we could add a separate filter for the Layout Widget.

It allows, for example, a custom post type to have a content Layout Widget where their users could build the content for the post. In this case, we don't want them to edit the main post type structure, but we do want to allow the users to edit the layout that represents the post's content.

**Comment by AlexGStapleton** [comment]
Ah. Gotcha - thought it was unintentional. A separate filter would definitely be a good idea.
