### ISSUE TITLE
Plugin conflict with Jetpack (breaking Leaflet Maps Marker / Maps Marker Pro maps as a result)

### ISSUE THREAD

**Issue by robertharm** [siteorigin/siteorigin-panels#443]
I am the developer of the mapping plugins Leaflet Maps Marker (https://wordpress.org/plugins/leaflet-maps-marker/) and Maps Marker Pro and users reported a plugin conflict involving your plugin - I hope you can help, although this seems to be a tricky issue:

my plugins are shortcode based, maps get created if you add a shortcode like [mapsmarker layer="1"] to posts or pages. The issue now reported is, that if such a shortcode is added to a "SiteOrigin Editor" widget and if Jetpack is active with the option "Add sharing buttons to your posts" (wp-admin/admin.php?page=jetpack#/sharing) active, then maps break. See example at https://dev.mapsmarker.com/free/2017/07/09/siteorigin-jetpack-issue-with-maps/ - the issue is, that somehow Jetpack is duplicated the JS output created by my mapping plugins if this option is enabled.

This issue only happens though if my shortcode is used within a "SiteOrigin Editor" widget - if I use the same shortcode with the regular Wordpress editor, everything works fine. See example at https://dev.mapsmarker.com/free/2017/07/09/layer-1-regular-usage/

It would really be great if you could have a look, as for me this seems like a general issue with SiteOrigin & Jetpack.

**Comment by AlexGStapleton** [comment]
Based on the output, this issue appears to be related to the editor you're using rather than Jetpack. To clarify, what happens if Jetpack is completely disabled? Does it work without issue?

Also, ddes this issue resolve itself if you open the SiteOrigin Editor widget and untick **Automatically add Paragraphs**? If not, try enabling Content Cache by navigating to **WP Admin > Settings > Page Builder** and open the **Content** tab. Tick Content Cache and save. Does this issue still occur?

**Comment by robertharm** [comment]
Hi Alex,
thanks for the input & sorry for the late reply - as we are currently preparing a major rewrite we could also workaround this compatibility issue, which we could not reproduce anymore with our 4.0 dev version - so this issue can be closed...
