### ISSUE TITLE
Reader view breaks when using page builder

### ISSUE THREAD

**Issue by MarkHjorth** [siteorigin/siteorigin-panels#480]
Reader view no longer works after I have moved my content from the default editor in Wordpress to the SiteOrigin Page builder.

### How to Replicate:
1. Go to [the website](https://markhjorth.com/portfolio/games/goblins-ruin-rpg-mobile-game/)
2. In Safari press "Show reader view"
3. Only content that is not from page builder is shown (Title, Author, Date and Featured Image)

### Example shown below:
![screen shot 2017-10-24 at 21 01 31](https://user-images.githubusercontent.com/7202633/31962730-a82869fc-b8fe-11e7-8291-822bcc76dd79.png)

### Additional information:
**OS:** macOS 10.13 - High Sierra
**Browser:** Safari 11.0
**Wordpress:** Wordpress 4.8
**Page builder:** Version 2.5.13

**Comment by AlexGStapleton** [comment]
Unfortunately, this is sadly unavoidable due to the way the reader view (and similar browser plugins/services) detect content. There's no way for us to tell it what's actually content as it works everything out automatically and their system for working things out is imperfect due to a lot of assumptions it makes. 

Everything currently displaying are the only things you actually can tell it to use which is why they're working without issue.

Unfortunately, this isn't something we can fix. I'm sorry.
