### ISSUE TITLE
Custom HTML Widget: Not Editable in 4.9

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#487]
The core Custom HTML Widget added in 4.8.1 is not editable in Page Builder in 4.9.
Existing content is being displayed but the widget is no longer editable in Page Builder.

**Comment by Metatrox** [comment]
Yes I am having the same issue.
The widget preview shows my "Custom HTML" content but when you click the edit the popup doesn't show the HTML code.

**Comment by Misplon** [comment]
Thanks for reaching out @Metatrox. We'll get this sorted ASAP tomorrow. Sorry for the hassle.

**Comment by itsgrimace** [comment]
I am no expert but I'd say the problem is evident in the changes to the WP widget classes.
previously there was a function 
public function form( $instance ) which pulls the widget current settings and i think it may have pulled the layout as well. Now there are 2 functions (thanks to the comments)
public function form( $instance ) - this pulls the current settings
&
public static function render_control_template_scripts() - this includes the html render script

see  [https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/widgets/class-wp-widget-custom-html.php#L235](https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/widgets/class-wp-widget-custom-html.php#L238)

**Comment by simplecreatif** [comment]
In the meantime, what is a good solution if we need to make edits to pages using the Custom HTML widget...? Rollback to the previous version of Page Builder? Or is it better to wait for the next release for the fix?

**Comment by itsgrimace** [comment]
The problem is the changes to the custom HTML widget in wordpress. You would need to roll back your WP installation. A work around I do have however. Using an editor program write your html. Then copy it and load the widget's edit page in chrome. right click the center (where html would go) then click inspect. This will bring up the inspector. Edit the line of HMTL which is like this;

`textarea id="widget-custom_html-c24-content" name="widgets[c24][content]" class="content sync-input" hidden="">&lt;p&gt;lame text here&lt;/p&gt;</textarea>`

remove the hidden="" part and then click off. This will give you an exit box, its small so don't expect much...

**Comment by simplecreatif** [comment]
Excellent work around for the time-being, not pretty - but it'll work for urgent changes, thanks heaps mate!

**Comment by itsgrimace** [comment]
ok so maybe because I'm bored but I think I have found exactly where things might need to change.

the file is js/siteorigin-panels/view/widgets/js-widget.js

In there there are options to handle, media widgets and a text widget, no option however for some of the new widgets added in 4.9 (as in added to the widgets folder in WP). I might take a punt here and suggest that a custom_html widget will render similar to a text widget so;

ammending `CUSTOM: 'custom_html',` after line 8 then adding `case this.CUSTOM:` after line 19 might fix? 

see how you go... I am not a php or js developer so this is the best I could come up with. I used issue #420 to get to this point...

**Comment by Misplon** [comment]
Thanks for looking into this guys. We're working the issue now. Release to follow. Appreciate the help.

**Comment by Swagatam1975** [comment]
I was facing the same issue in my Genesis theme, after a lot of investigation I realized that it was happening due to the custom "defer javascript" code which I had placed in my .functions.php. On removing this code the issue was instantly solved.
So guys it is a theme issue, check all the custom php codes that you might have added in your .functions.php, one of them could be causing the problem.

**Comment by karlinexcode** [comment]
I have issues with my widgets I can't make custom codes on my website. It just stays like that keeps loading for days I have tried all I can nothing seems to be working, I have tried adding custom code banners etc, Just anything requiring me to use code doesn't work.. Please what is the fix to this?
![image](https://user-images.githubusercontent.com/71902157/125466542-5f5a2e69-d406-48cb-8e09-19c94e05dac1.png)

**Comment by Misplon** [comment]
Hi @karlinexcode 

Thanks for reaching out. 

This GitHub issue is closed. The widget being used in your screenshot is a core WordPress widget. 
Kindly, post your question on our support forum at https://siteorigin.com/thread. We'd be happy to lend a hand and advise on troubleshooting steps that can be taken.

Kind regards

Andrew
