### ISSUE TITLE
Conflict with Symple Shortcodes plugin

### ISSUE THREAD

**Issue by viktorix** [siteorigin/siteorigin-panels#49]
Symple Shortcodes plugin inserts a new TinyMCE button, with a dropdown for shortcodes. Once Page Builder is activated for a specific post type (post, page), Symple Shortcode's button disappears from TinyMCE.
https://github.com/wpexplorer/symple-shortcodes

**Comment by CybMeta** [comment]
Same problem here.

**Comment by Misplon** [comment]
Hi guys, it doesn't look like Symple Shortcodes has been updated since Version 2.1.3 – November 8, 2016. We're pretty constrained with resources at the moment. If the developer of Symple Shortcodes would like to help out then we can try to assist. Otherwise, unfortunately we'll close this for the moment. Sorry we weren't able to attend.
