### ISSUE TITLE
Text widget - autop

### ISSUE THREAD

**Issue by gabor1990** [siteorigin/siteorigin-panels#522]
Hi! Recently we are getting a lot of email about the same issue, that you have an option at the text widget called "Automatically add paragraphs" which inserts empty paragraphs into our shortcode made code as well.
Is there a way this could be avoided? Because users are using all kind of shortcodes, not just ours and automatically adding paragraphs to their own texts might gives a good result, but I don't think the same applies to html codes made by shortcodes.

**Comment by AlexGStapleton** [comment]
Hi gabor1990,

We've come across this issue a few times in the past and we definitely keen on fixing this issue - we consider it quite a serious one. Can you please clarify the name of your plugin? I ask because we're looking for reliable methods of replicating this issue, and as your plugin is affected by this issue it can definitely help us in doing that.

Unfortunately, outside of disabling Automatically Add Paragraphs, we're not aware of a reliable method of avoiding this at this time. Although, based on what we've found so far, this issue only seems to only happen when JavaScript is added directly via the shortcode so this might be avoidable by enqueuing the JavaScript instead.

To clarify, is your shortcode having issues in the Text widget also?

**Comment by nextend** [comment]
Hi Alex, thank you for checking this issue! You can use Smart Slider 3 to reproduce the issue.

Add Smart Slider 3 as shortcode to the text widget and it should modify the content of the slider. As I remember we saw the issue when we have embedded svg in the slider with shape divider. Get in touch with me and I will give you a pro license to Smart Slider and I will send you a slider to import which will produce the issue. roland@nextendweb.com

BTW, why don't you prioritize shortcode and autop into the right order? Autop should happen first and then the shortcode.

**Comment by Misplon** [comment]
Thanks everyone, let's move this over to the Widgets Bundle repo, link above.
