### ISSUE TITLE
row and cell styles display issue (backend)

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#530]
There is a CSS issue in the page builder admin.css, which pushes the cell style options out of view.

This is a minor issue by itself, but because not all users know how to set cell styling (you need to click on the cell first) and now even if they click on the cell, they can't see the cell styling options.

There is the line which reads:
```
.so-panels-dialog .so-visual-styles {
    margin: -15px;
    height: 100%;
}
```
While it actually should be:
```
.so-panels-dialog .so-visual-styles {
    margin: -15px;
    height: auto;
}
```
Here is the video for clarification: http://jmp.sh/gDgpr12
and an image:
![screen shot 2018-04-26 at 13 36 14](https://user-images.githubusercontent.com/10053621/39303570-f5dda1a6-4956-11e8-884d-bc876765f0e3.png)

**How to reproduce:**
Hard refresh the backend, to make sure the latest admin.css is loaded. Add a row, click on the cell.

**Comment by AlexGStapleton** [comment]
Unfortunately, we can't replicate this with a fresh install. As such, we suspect this is a general conflict with something that just so happens to be fixed by this change. Regardless, I can't see any direct issues with making this change so I don't see any harm in making this change.

Would you be willing to submit a [PR](https://help.github.com/articles/about-pull-requests/) for this? If not, I can submit one for you.

**Comment by andrejarh** [comment]
Sure. :)

**Comment by gregpriday** [comment]
See the fix for this has already been merged.
