### ISSUE TITLE
Gutter disappears at mobile size even when `No Collapse` is selected

### ISSUE THREAD

**Issue by petemolinero** [siteorigin/siteorigin-panels#564]
When `Collapse Behavior`: `No Collapse` is selected, I would expect the gutter to remain intact at the mobile size. Unfortunately, it actually disappears, leaving the columns touching each other.

**Comment by AlexGStapleton** [comment]
This is happening because we're setting the cells to 100% width on mobile. 

![](https://i.imgur.com/4AkCdeo.png)

I can't seem to find the source of this CSS, or I would submit a PR for it. I'll take another look for it later tonight.

**Comment by AlexGStapleton** [comment]
Hi Pete,

Very sorry for the delay.

We've looked into this issue. While this issue is very unfortunate,  it's not currently a priority due to lack of overall reports and complexity required for the fix for this issue. I'm going to close this issue for the time being and we'll come back to it at a later date when we resolve higher priority issues.
