### ISSUE TITLE
Prefix all generic page builder editor classes

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#608]
This is a replacement to #607.

We're using a number of generic classes that can overlap with other plugins/themes. Classes like `title`, `description`, `cell`, `action` can easily be used by other plugins so to prevent potential issues, we should prefix these classes.

**Comment by Misplon** [comment]
@AlexGStapleton To move this forward, perhaps go through Braam's feedback from #607 and answer here. If you can get the classes decided on, you can then proceed with a PR.

@braamgenis This problem is consisetly raising support tickets. If we could avoid the problem even though we're not directly at fault, it would be a great time saver. Thanks mate.

**Comment by Misplon** [comment]
Let’s decide on the list of names to be changed. Please make a list here,
old name then new name. We can run that past Braam. Or do you want to do
that in a PR?

Braam?

**Comment by gregpriday** [comment]
Unless there's a direct conflict happening with a big plugin, which from https://github.com/siteorigin/siteorigin-panels/pull/607#issuecomment-442703369 I assume there isn't, then I'd rather not do this. It'd require a fair amount of testing and opens us up to other unforeseen issues.

What we have now is well tested and not causing issues.
