### ISSUE TITLE
.. CPU / Ram Usage

### ISSUE THREAD

**Issue by Frumph** [siteorigin/siteorigin-panels#63]
Trying to trace where this 'mero page builder' plugin is coming from with the theme Elano, points me to http://siteorigin.com/page-builder/ then at the bottom this github.  So i'm guessing this is the same just renamed for that theme?

Anyways if it is; there's a huge ram/processor load when running the page builder and wondering if you guys have seen it before and might know what I can do.  I am thinking I can strip out their mero page builder (why it's renamed no idea) and use the one from siteorigin instead?

**Comment by gregpriday** [comment]
Hi Frumph

We have seen quite a few theme developers fork our plugin. Often to sell as a paid feature. A few of them didn't update the URLs so they're still pointing to us.

Unfortunately it's very difficult for us to know when they forked our plugin and what they've added/changed since the fork. We have some frontend performance issues with very large pages around version 1.4, but we fixed these issues about a year ago.

The best suggestion I can come up with is to ask the Mero guys to help you switch to SiteOrigin Page Builder. As far as I'm aware, our version more actively developed than any of the forks.

**Comment by Frumph** [comment]
Appreciate the response and going to point him towards this post as well if that's okay with you.   If they were forking around 1.4 that would be the case I am going to assume.
