### ISSUE TITLE
Widgets displaying ID instead of description or content

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#644]
At times, widgets seem to be displaying their ID instead of a human-readable description.

<img width="592" alt="edit_page_ _siteorigin_ _wordpress" src="https://user-images.githubusercontent.com/789159/52913119-6837a700-32c3-11e9-8383-baa8726d8f9a.png">

Here is the JSON layout for the page.
https://www.dropbox.com/s/7esd260ttidi680/page-builder.json?dl=0

**Comment by gregpriday** [comment]
This is a long standing limitations with how that description is fetched. It basically looks at fields inside the widget and tries to assign something as the title.

In the case of the layout you uploaded, the tabs widget doesn't have a title, so it looks for another first level field. I remember there being issues with trying to go deeper into repeaters to get the values. These values are also fetched based on what's stored in the database, because it happens before the forms are loaded.

Unless we can think of a good way to detect usable titles, this is the best option. I've added a check to skip fields that satisfy `if(k.charAt(0) === '_' || k === 'so_sidebar_emulator_id'  || k === 'option_name')`, to filter out common WB support fields. So now it'll fall back to the widget description.

**Comment by Misplon** [comment]
The check sounds great for this situation. Thanks.
