### ISSUE TITLE
Yoast Compatibility code isn't working in the Block Editor

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#647]
The Yoast Compatability code isn't currently working in the Block Editor. These sort of issues don't affect SEO but do tend to increase the overall support load users questioning why this issue.

Classic Editor (SiteOrigin Page Builder):
![](https://i.imgur.com/mHJMHxb.png)

Block Editor (SiteOrigin Layout widget):
![](https://i.imgur.com/QBQzCvH.png)

[Test Layout](https://siteorigin.slack.com/archives/C02SYBBH2/p1551210427001900)

**Comment by braamgenis** [comment]
I've looked into this quite extensively and there are a few hurdles to overcome to get this working:
- We need to have some version of the layout block's rendered content in blocks attributes. 
- In the [Yoast compat](https://github.com/siteorigin/siteorigin-panels/blob/2.10.2/js/yoast-compat.js#L35) content modification plugin we need to parse out blocks, retrieve the rendered content mention above, and run it through the content modification code to handle the various widgets' content. Basically the same thing we're doing for each page at the moment in classic editor, but for each SO Layout Block.

The second step is where I got stuck as the block attributes seems to be half-encoded with only left angle brackets (`<`) being encoded. So would need to do some very careful decoding of the surrounding HTML without also decoding widget shortcodes' content. Due to time constraints, we're putting this on hold for the moment.
