### ISSUE TITLE
Multiple Page builders on one page

### ISSUE THREAD

**Issue by Jab2870** [siteorigin/siteorigin-panels#651]
Hi,
Thanks for creating this plugin.

I have a page that currently has two tinymce editors. One is the main content of the page and one is custom meta. My question is this: is it possible to use the page builder for both of these sections on one page?

**Comment by AlexGStapleton** [comment]
Hi Jab2870,

This is quite tricky to do so unfortunately I can't provide direct instructions on doign this but I can highlight the code we use to do this and provide examples of where we're doign this.

SiteOrigin Page Builder is designed to to attach to any div that has the `siteorigin-panels-builder-form` class. This is handled [here.](https://github.com/siteorigin/siteorigin-panels/blob/2.10.1/js/siteorigin-panels/main.js#L92-L107).

Here's some examples of this being done:
[Layout Builder](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/widgets/layout.php#L102-L117
)
[Admin Home Page](https://github.com/siteorigin/siteorigin-panels/blob/develop/tpl/admin-home-page.php)
[SiteOrigin Widgets Bundle Builder form field](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/inc/fields/builder.class.php#L20-L35)

[Main Page Builder Template
](https://github.com/siteorigin/siteorigin-panels/blob/develop/tpl/metabox-panels.php) (this is more as an general example rather than somethign you should directly replicate as it's setup slightly differnetly)

**Comment by Misplon** [comment]
Closing for the moment. Jab2870, if you have any follow-up questions, please let us know. Thanks.
