### ISSUE TITLE
YoastSEO.js: Add further Yoast compatibility for remaining WB widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#675]
The following widgets are currently not added to the [Yoast Compatability code](https://github.com/siteorigin/siteorigin-panels/blob/2.10.5/js/yoast-compat.js):

- Call-To-Action
- Contact Form
- Features
- Google Maps
- Headline
- Hero Image
- Icon
- Image Slider
- Layout Slider
- Post Carousel
- Price Table
- Social Media Buttons
- Testimonials
- Taxonomy
- Video Player

For reference, the following widgets are currently accounted for:

- Image
- SiteOrigin Image
- SiteOrigin Image Grid
- SiteOrigin Simple Masonry
- SiteOrigin Accordion
- SiteOrigin Tab
- SiteOrigin Button
- Text
- SiteOrigin Editor

**Comment by gregpriday** [comment]
Adding custom rendering logic to each widget does get really messy.

We have 2 options here. The first would be to make server requests for the HTML for each unsupported widget as a fallback. This could be really slow though.

The other option would be to dump out all the field values to give Yoast a better chance at picking up text within the widget form.

**Comment by braamgenis** [comment]
> make server requests for the HTML

I had something like this going in the block editor when trying to solve #647 but with a request for the whole layout's HTML. We already fetch a layout's HTML in the classic editor when _Copy Content_ is enabled, so don't think it'd take too much effort to use that here.

**Comment by gregpriday** [comment]
I had a look at this. So the main issue is that the layout's HTML in the classic editor is encoded in a way that makes it possible to decode back into a full `panels_data` object. This is what we're already passing to our Yoast compatibility code.

So we have a few possible solutions:

* Pick the most important widgets to add some more custom JS processing code.
* Make additional server requests to get the full processed HTML for each widget. If we add these requests to our Yoast compatibility code, then they'd need to be blocking to ensure we return the proper HTML. This isn't ideal, but we could use caching to speed things up.
* Give the user the option to change the behaviour of the `so_panels_builder_content` action so that it returns full HTML. This is the easiest solution and lets the user decide on the tradeoff. Do they want better Yoast compatibility, or do they want to be able to go to and from the classic editor. This is a quick 30 minute solution.
* We could come up with a hybrid solution. So have `so_panels_builder_content` return fully processed HTML, plus store widget data in HTML comments. This could give us the best of both worlds, but it's really finicky.

Any suggestions on which solution would be best?

**Comment by braamgenis** [comment]
The last solution seems like the best option as it might solve, at least partially, #647 too. In the end it depends on how much time you want to spend on this. If the answer is "not much" then option 3 seems like a good alternative, albeit with a tradeoff.

**Comment by gregpriday** [comment]
I added a `so_panels_builder_content_json` action that also returns a content preview, which Yoast compat can then use. This is added to the main builder view [here](https://github.com/siteorigin/siteorigin-panels/blob/feature/improved-yoast-compat/js/siteorigin-panels/view/builder.js#L747).

This makes all widget compatible in the classic editor. @braamgenis, could you use this to get content passed to Yoast in the block editor for #647?

**Comment by Misplon** [comment]
Thanks, G. I'm using the Corp default home page as a demo right now. You can use that same layout by activating Corp and then checking Prebuilt Layouts.

The first image below is from the develop branch:

![default](https://user-images.githubusercontent.com/789159/62321060-0bf7c680-b4a2-11e9-9203-0e4c2776f34f.png)

The second image is from our new feature compatibility branch:

![new](https://user-images.githubusercontent.com/789159/62321076-14e89800-b4a2-11e9-8db8-25196d47c09f.png)

Nine words changes to 203, awesome. But for some reason, the compatibility branch doesn't pick up the outbound link which the develop branch does. The outbound link can be found within the first Hero widget's button. The link is https://wordpress.org/themes/siteorigin-corp/. Any ideas?

**Comment by Misplon** [comment]
Outbound and inbound links are being detected within the Editor widget. However, they don't appear to be detected within the following widgets:

Hero (have added links to the frame content field and the button field)
Headline (have added destination URLs to the main and sub-headline)
Button

They also aren't detected from the Post Carousel widget but I'd imagine that's expected.

**Comment by Misplon** [comment]
The outbound and inbound link issues appear to be consistent. In the Accordion widget, the key phrase is detected in the content field but outbound and inbound links aren't detected in that same field.

**Comment by braamgenis** [comment]
@gregpriday I managed to use the action you added to get Yoast's analysis working in the block editor by using the block's `save` function. Everything still seems to work after some cursory tests, so I think that did the trick!

**Comment by Misplon** [comment]
Epic! That's great news.

**Comment by mackembob** [comment]
Can anyone confirm that this issue only affects the block editor and not the classic editor for the widgets outlined in the OP? Thanks

**Comment by Misplon** [comment]
Hi, the Block Editor issue is separately logged https://github.com/siteorigin/siteorigin-panels/issues/647. In the initial posting of this issue, Alex lists the widgets that are sending to data to Yoast at the moment and those that aren't. That applies to both the Classic Editor. Hope this helps.

**Comment by mackembob** [comment]
Thanks.  

So, currently neither editor is working fully with Yoast.  

Having had a read through the thread, I think option 3 proposed by Greg would be the best option for most scenarios - _Give the user the option to change the behaviour of the so_panels_builder_content action so that it returns full HTML. This is the easiest solution and lets the user decide on the tradeoff. Do they want better Yoast compatibility, or do they want to be able to go to and from the classic editor. This is a quick 30 minute solution._

**Comment by Misplon** [comment]
Sure.

At different levels. The Classic Editor has a limitation in terms of the widgets that send data to Yoast. The Block Editor has a bug.

Thanks for your feedback. I'm sorry we haven't had the resources to complete this yet. It's definitely very high on our to-do list and will be completed as soon as we're able to.

**Comment by mackembob** [comment]
No problem at all, I'm just trying to understand where things stand.  I'm really not meaning to hassle you guys. :-)

**Comment by Misplon** [comment]
No worries, not hassling at all, we'd really like to see this resolved, the problem has just been quite challenging. Thanks for checking in. Feel free to reach out at any time, either here, on the forums at https://siteorigin.com/thread/ or via email on support@siteorigin.com if you're using SiteOrigin Premium. Cheers for now :)

**Comment by jtibbles** [comment]
Currently SiteOrigin and Yoast are incompatible due to the "0 words" count. Can I fix this by switching off Guternberg and using classic editor instead?

**Comment by Misplon** [comment]
Hi, @jtibbles. Thanks for reaching out. The Classic Editor offers limited compatibility. Please, see the list provided by Alex at the very top of this issue. If you have any follow-up questions, kindly, open a support thread on our [forum](https://siteorigin.com/thread), we'd be happy to lend a hand.

**Comment by TheRed-E** [comment]
Currently the SiteOrigne Button is also not recognized if using the "select content" option, which shows Post: #post number#. Only Direct URL's are recognized as internal/external links by YOAST.

**Comment by Misplon** [comment]
Thanks for letting us know.
