### ISSUE TITLE
Layout Block Removed: Conflict with WPSSO Core

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#677]
To replicate, activate https://wordpress.org/plugins/wpsso/. 
Create a Block Editor page.
Check the Console. The Layout Block is missing.

`Uncaught SyntaxError: Identifier 'RawHTML' has already been declared
    at siteorigin-panels-layout-block.js?ver=dev:1`

**Comment by braamgenis** [comment]
This is being caused by wpsso using `const` to declare a `RawHTML` variable in the global scope. Then the error occurs when our block tries to redeclare `RawHTML` as a `var`. `const` doesn't allow an identifier to be reused if it already exists in a scope, where `var` does. Blocks, like the Layout Block, which are compiled using something like Babel would have their global `const` declarations converted to `var`, so this conflict won't occur between the Layout Block and other blocks, but it likely will occur between WPSSO and other blocks.

**Comment by Misplon** [comment]
I've updated the reporting thread: https://siteorigin.com/thread/wpsso-plugin-not-compatible/. Thanks Braam.
