### ISSUE TITLE
Forminator: Load form using AJAX with Yoast SEO breaks shortcode output

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#679]
To recreate the conflict:

1. Activate Yoast SEO.
2. Activate Forminator, create a form, edit form settings, in the Behavior section scroll down to Rendering and enable Load form using AJAX.
3. Insert the form into Page Builder using the form shortcode.

In this configuration, the form doesn't load. If Yoast SEO is deactivated or if Load form using AJAX is disabled, the form will load. No console or PHP errors could be found. I couldn't find any specific Yoast SEO settings that changed the outcome.

**Comment by Misplon** [comment]
Checked. This issue remains the same 27th July 2019.

**Comment by AlexGStapleton** [comment]
This issue is caused by Yoast loading a copy of the pages content to generate the Open Graph description. Specifically, this line:

https://github.com/Yoast/wordpress-seo/blob/2e6b272ad62001a05ca113e35a1205376058f9c4/src/presentations/indexable-post-type-presentation.php#L191

That line triggers the_content and Forminator likely has a check that prevents it from running twice and that's causing issues. I'll investigate Forminator's side of things shortly to see if this check can be accounted for.

It should be noted that this issue can be avoided by manually setting a meta description.

**Comment by AlexGStapleton** [comment]
I've looked into this further and I don't see a simple way for us to resolve this issue without doing somethings we ideally shouldn't do (like removing their shortcode briefly and re-adding it, or forcing their assets to output twice). We should recommend users either set a manual meta description or disable Ajax Loading.

**Comment by Misplon** [comment]
Thanks, mate. Do you perhaps want to add a paragraph here for us? https://siteorigin.com/page-builder/troubleshooting-problems/.

**Comment by AlexGStapleton** [comment]
How does that look?

**Comment by Misplon** [comment]
Sorted. Thanks.

**Comment by AlexGStapleton** [comment]
Re-opening due to https://github.com/siteorigin/siteorigin-panels/pull/910
