### ISSUE TITLE
Notice in SiteOrigin_Panels_Renderer::get_panels_data_for_post

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [siteorigin/siteorigin-panels#692]
![Screenshot from 2019-08-21 17-49-19](https://user-images.githubusercontent.com/1181261/63467648-55518b00-c43c-11e9-9a8e-4288d4e90216.png)

This happen when `SiteOrigin_Panels::is_live_editor()` is true and `$_POST['live_editor_post_ID']` is not equal `$post_id` becouse `$panel_data` is defined only inside the second if.

**Comment by AlexGStapleton** [comment]
Unfortunately, I can't replicate this error. Are you able to consistently replicate this issue or does it only happen after a specific action?

Would it be possible for you to send me an export of the layout this issue is occurring with? To export a page, please open up the page in the editor and click the Layout button in the Page Builder toolbar. Then click import/export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://wetransfer.com/">WeTransfer</a>  (no email is required).

**Comment by AlexGStapleton** [comment]
Hi @rafaelchavesfreitas ,

I haven't heard from you so I'm going to close this issue to clear the queue. Let me know if you would like to pick this back up again and we'll work out what's going wrong.
