### ISSUE TITLE
Parallax: Update to use transform

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#727]
Considering improving performance and usability by switching parallax from background-position to transform.

https://developers.google.com/web/updates/2016/12/performant-parallaxing

**Comment by AlexGStapleton** [comment]
Do you want me to try and minimize the number of additional divs used, or are the 3 divs Google uses okay?

The library Google came up with (which is linked at the very end of the article you posted) looks to move the parallax to a separate div and reduces the overall number of elements.
([demo here](https://googlechromelabs.github.io/ui-element-samples/parallax/) - [code here](https://github.com/GoogleChromeLabs/ui-element-samples/tree/gh-pages/parallax)).  The library also handles the calculations which prevents us from having to do that. 

Both the article and the library they came up with are from 2016 so it might be worth checking if there's a more modern library/technique. Do you agree? If so, I'll take a look around.

**Comment by Misplon** [comment]
Look around, please.

**Comment by AlexGStapleton** [comment]
It seems most parallax libraries ignore CSS backgrounds in favor of HTML images. I can definitely understand their reasoning for this (main reason likely being actual control over the sizing of the image without fighting `background-size: cover;`). The only libraries I could find that supported CSS backgrounds were either dead in the water (no updates for a number of years with a tonne of pending pr and issues), used partial implementations, or used `background-position`.

It might be worth considering outputting the image directly rather than using a background. If you would (understandably) rather not take this path, we'll need to implement the versions highlighted in the above Google links.

if you want to consider the HTML Image route, here are some popular options:

https://github.com/geosigno/simpleParallax.js/
Focused on HTML images. Scaling options, but nothing mobile specific. Actively supported.

https://github.com/dixonandmoe/rellax
Has mobile-specific scaling. Actively supported.

**Comment by Misplon** [comment]
Sounds like using the Google option is the best overall choice for us at the moment.
