### ISSUE TITLE
Layout Export exports a empty layout because of plugin conflicts

### ISSUE THREAD

**Issue by KevinTaron** [siteorigin/siteorigin-panels#820]
Since a new update we have problems to export the pagebuilder layout. 
The exported layout is always empty. Javascript Console error:

"siteorigin-panels.min.js?ver=2.11.4:1 Uncaught TypeError: Cannot read property 'getSelectedBlockClientId' of null
    at i.getCurrentBlockPosition (siteorigin-panels.min.js?ver=2.11.4:1)
    at HTMLFormElement.<anonymous> (siteorigin-panels.min.js?ver=2.11.4:1)
    at HTMLFormElement.dispatch (load-scripts.php?c=0&load[chunk_0]=jquery-core,utils&ver=5.5.1:3)
    at HTMLFormElement.r.handle (load-scripts.php?c=0&load[chunk_0]=jquery-core,utils&ver=5.5.1:3)"

This happens only with some plugins activated. 
For example: Rank math SEO or Advanced Editor Tools (previously TinyMCE Advanced).

**Comment by AlexGStapleton** [comment]
Hi Kevin,

Thank you for your report. This issue is fixed in https://github.com/siteorigin/siteorigin-panels/pull/817, and will be available in the next PB update. You can download a beta version of the next release by [clicking here](https://github.com/siteorigin/siteorigin-panels/files/5304363/siteorigin-panels.2.11.5-beta.zip).

Kind regards,
Alex

**Comment by KevinTaron** [comment]
Hey Alex,

my bad. Didn't saw that.

BR Kevin

**Comment by AlexGStapleton** [comment]
Hi Kevin,

No worries mate. Thanks for reporting this issue anyway. 👍 

Kind regards,
Alex
