### ISSUE TITLE
Using CSS to Prevent Container Breaker CLS

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#866]
We've received a few reports of the container breaker causing [CLS](https://web.dev/cls/) issues. This is due to the unavoidable delay before the container breaker JavaScript is run simply due to how the DOM works - it's out of our hands.

There is, however, a way to avoid the CLS and that's by using CSS instead of JavaScript. Basically, we remove the theme container globally and then apply it as needed. This removes the need for the container breaker code so there's no "jump" shortly after the page starts loading as a result of it.

### Settings
To accomplish this using CSS, we'll need to introduce two new settings to the Page Builder Layouts tab. These settings will be quite technical as there's no way for us to automate them as automating them will result in a CLS impact. These settings are:

**Theme container selector**
The setting is used for overriding the theme container. This is done on load using CSS rather than CLS and it's going to be done with a high priority `wp_head`.

**Theme Container Width**
This setting is the exact width of the theme container. This cannot be calculated on the fly using the theme container selector as that'll result in a CLS due to the delay before it's able to be calculated and applied.

If both of the above settings are applied, we'll remove the container breaker JS (this would technically resolve https://github.com/siteorigin/siteorigin-panels/issues/557) and manually apply row sizing as needed using CSS.

### How We'll Use Those Settings to Avoid the CLS

For rows that are set to Full Width Stretched, no container is applied.

For full width rows, we apply the container width to either `.panel-row-style`, or a container inside of `.panel-row-style` (using `siteorigin_panels_inside_row_before` hook). This is the most complicated Row Layout and will require the most overall testing.

For standard rows, the container width is applied to `.panel-grid`.

The container width is always applied using `max-width` to avoid potential responsive issues.

### Possible Hooks for Themes

We could allow themes to pre-fill container settings. This will remove the technical concerns and make the process much simpler overall. Those fields could be called: `siteorigin_panels_default_theme_container_selector` and `siteorigin_panels_default_theme_container_width` 

### Final Thoughts

The CSS approach is the best way to resolve the CLS reports. This is, however, quite a technical change and there's no real way around that. There will be older themes that are simply not compatible with it, and there's no real way for us to get around that potential situation outside of recommending users change to a more modern theme.

**Comment by AlexGStapleton** [comment]
@Misplon Let me know if you have any questions or suggestions.

**Comment by AlexGStapleton** [comment]
I've spoken to @Misplon about this over Slack.

The settings required to do this are both required and that's quite unusual as no other Page Builder setting so heavily depends on another setting like this (there are similar settings, but they have defaults that they fall back on if only one is set). To make this more apparent we're going to introduce a custom setting type that will display the fields differently from the other fields. That setting type will be based on the Widgets Bundle [Multi Measurement](https://siteorigin.com/docs/widgets-bundle/form-building/form-fields/#heading-multi-measurement) form field ([screenshot](https://siteorigin.com/wp-content/gh-docs/docs/widgets-bundle/images/form-field-type-multi-measurement.png)). The currently setting structure will be:

```
Setting label
Setting description
Setting Setting
Field.   Field
```

**Comment by atrzyna** [comment]
This sounds great. I hope you guys get the fix implemented soon. I found a workaround where we fade in the row with a delay of 100ms but this is not ideal.

**Comment by AlexGStapleton** [comment]
Hi @atrzyna,

I've submitted a PR that implements what I've outlined in this issue and that can be found here:

https://github.com/siteorigin/siteorigin-panels/pull/911

We're currently testing this PR, and if you are interested, I'll send you a build for you to try it once the first round of testing has finished.

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi @atrzyna,

I've created a build of [the current version of this change](https://github.com/siteorigin/siteorigin-panels/pull/911). You can download it by [clicking here](https://drive.google.com/uc?id=1xdffrTyqxwZ7AVxsY4aIAxpZPYJ0PqrT). You can install it by navigating to **Plugins > Installed Plugins** and deactivate Page Builder by SiteOrigin, and then delete it. Scroll to the top of the page and click **Add New**, **Upload Plugin**. Upload siteorigin-panels.2.13.2.1.zip and when prompted, activate Page Builder by SiteOrigin.

To enable this change you'll need to use the `siteorigin_panels_theme_container_width` and `siteorigin_panels_theme_container_selector` filters to set your container width (ie. `1170px`) and container selector (ie. `.site-content .corp-container`) so that Page Builder is able to override your theme container and re-apply it at the row level. An example of this for the [SiteOrigin Corp theme](https://wordpress.org/themes/siteorigin-corp/) is:

```
add_filter( 'siteorigin_panels_theme_container_width', function( $container ) {
	return '1170px';
} );

add_filter( 'siteorigin_panels_theme_container_selector', function( $selector ) {
	return '.site-content .corp-container';
} );
```

If you need some assistance with identifying the values for these two filters, please send me a link to the website you're testing this build on.

Kind regards,
Alex

**Comment by atrzyna** [comment]
Hi @AlexGStapleton,

Thanks for sending the build to test. I found some issues with padding, tablet and mobile breakpoints. 

I made a container called grid-container-holder which limits the width of the page, excluding the header and footer. It is only used for the content between header and footer. We build our themes using Foundation css framework but i didn't want to have the global grid-container used in foundation css overwritten by the page builder so i made a brand new container. 

Template: 
`<?php

get_header();

?>

  <div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">
      <div class="grid-container-holder">
          <?php
          while ( have_posts() ) : the_post();
              get_template_part( 'template-parts/content', 'page' );
          endwhile; // End of the loop.
          ?>
      </div>
      
    </main>
    
  </div>
  

<?php

get_footer();`

Grid container css:
`.grid-container-holder {
  max-width: 1170px;
}`

Filters:
`add_filter( 'siteorigin_panels_theme_container_width', function( $container ) {
    return '1170px';
} );

add_filter( 'siteorigin_panels_theme_container_selector', function( $selector ) {
    return '.site-main .grid-container-holder';
} );`

Here are screen shots of the js implementation vs the new css one. Ignore the padding on top and bottom of our full width rows. We add this by default in our theme. 

**Desktop:** This turned out to be identical. 
JS:
<img width="1680" alt="desktop js" src="https://user-images.githubusercontent.com/3791631/132960006-9f74a75c-29ef-4d57-85d5-06c1c16135dc.png">

CSS:
<img width="1680" alt="desktop css" src="https://user-images.githubusercontent.com/3791631/132960010-d8d40e36-91e6-4df6-a4e3-8527f9215626.png">

**Tablet:** The padding is gone from the right and left of full width rows and also the columns don't work the same way. Js version collapses the columns and css version keeps all 3 columns. 
JS:
<img width="811" alt="tablet js" src="https://user-images.githubusercontent.com/3791631/132960315-a2c9b67a-99e2-4255-9535-265641e76449.png">

CSS: 
<img width="812" alt="tablet css" src="https://user-images.githubusercontent.com/3791631/132960317-8ceef0df-d962-49a0-83d7-c0b790169edb.png">

Phone: The padding is gone from the right and left of full width rows and also the columns in the css version don't span the full width. 
JS:
<img width="510" alt="phone js" src="https://user-images.githubusercontent.com/3791631/132960360-6279294c-4c1e-4ea5-b07f-d48d50c54f7b.png">

CSS:
<img width="509" alt="phone css" src="https://user-images.githubusercontent.com/3791631/132960363-53fe668a-6daa-43f3-af22-fca88a1dc9e6.png">

I hope this is helpful. Once some of this is working better I can test rows within rows and more complicated layouts. Cheers

**Comment by AlexGStapleton** [comment]
Hi @atrzyna,

Would it be possible for you to provide a link to the pictured page? This will give me a better idea of your overall setup, and allow me to identify any padding being intentionally removed. I say intentionally, as the container padding is intentionally removed to allow for the rows set to full width to be full width (without it, there would be a gap on the sides). This padding will need to be [re-added using custom CSS](https://github.com/siteorigin/siteorigin-panels/pull/911#issuecomment-893674824).

Also, would it be possible for you to send me an export of the pictured page? This will allow me to run some tests against that layout to try and replicate these results. To export a page, open up the linked page in the editor and click the Layout button in the Page Builder toolbar. Click Import/export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://wetransfer.com/">WeTransfer</a>  (no email is required).

Kind regards,
Alex

**Comment by atrzyna** [comment]
@AlexGStapleton what is an easy way for me to get the urls and credentials for you to get into these sites? I would rather not post this info publicly.

**Comment by AlexGStapleton** [comment]
Hi @atrzyna,

No worries. Please send the details to support@siteorigin.com and include a link to this page.

Kind regards,
Alex
