### ISSUE TITLE
Add separate setting for panel bottom margin in Page Builder general options

### ISSUE THREAD

**Issue by frafor1988** [siteorigin/siteorigin-panels#931]
Hi there, this is a feature request.

I really enjoy working with SOPB however I often have to override via specific CSS rule the widget/panel's bottom margin to make it less than the row's bottom margin. Currently, the widget bottom margin is equal to the row's margin bottom.

I think it would be great to add a separate general setting for the widget/panel bottom margin in Settings > Page Builder.

Setting different margins would great for any website's UX because of basic design/element perception principles. The elements (panels) within a row would be closer to each other, meaning they're correlated one another. This perception would be comunicated at a first sight to the user, leading to a better experience and page readability. That's a basic gestalt psychology grouping mechanism (law of proximity).

What do you think?

**Comment by Misplon** [comment]
Hi @frafor1988 

Thanks for your kind message and request. We'll revert back in the week. Apologies for the delay.

**Comment by AlexGStapleton** [comment]
Hi @frafor1988,

It's great to hear you were able to come up with a solution that works for you. I've noted all of your feedback and we'll reference it internally for future updates.

> It is really unfortunate that there's a setting for what I am asking, but it works only for mobile devices and not for all devices

You can override the widget margin on a widget by widget basis for all devices by opening the widget and going over to the widget styles sidebar. Open the Layout settings group and set the Margin to your desired amount of spacing. https://github.com/siteorigin/siteorigin-panels/pull/939 adds the mobile version of this setting.

> Is it somehow possible to overwrite the widget margin for desktop layout via a filter too?

Yes. This can be done using the `siteorigin_panels_css_widget_css` filter you used in your second comment, and that is the correct approach.

> (Edit: later reading this, I understand that you're skipping it "at this time" so hope next time will be ok!)

We're "skipping" a dedicated global Mobile Margin setting at this time in favour of the widget specific margin and mobile margin settings. This is more down to lack of request rather than interest on our part as we're a small-time so we sometimes need to return to things like this.

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi,

Just saw your edit. Thank you for clarifying. That makes sense and I've noted your feedback. :)
I'm going to close this for the time being. We'll reopen it (or add a PR directly) in the future when we pick this backup. Please free to open another issue if anything else comes up.

Kind regards,
Alex
