### ISSUE TITLE
Use native WordPress Customizer instead of "live preview" mode

### ISSUE THREAD

**Issue by MatthewEppelsheimer** [siteorigin/siteorigin-panels#94]
An enhancement request. 

Since the live preview mode resembles the customizer but is different, there's an extra barrier for users to understand the difference and navigate between the two. 

It would be really nice for user experience to have them combined.

Would you be open to PRs that stitch them together?

**Comment by gregpriday** [comment]
Hi @MatthewEppelsheimer. I would definitely be open to somehow making this possible. Great idea.

Right now, I have a very rough idea of how this might work.

1. When the user clicks on live preview, save the current edits.
2. Load the customizer URL with 2 extra query arguments indicating the post_id and that it's a Page Builder view.
3. Clear out all the customizer controls and add a series of temporary sidebars representing current page builder columns.
4. When the user saves in the customizer, return to the main post editing interface with an extra argument that lets page builder know it must pull all the content out of these temporary sidebars.

Not sure this is the right solution, but it might work. Do you (or anyone else) have any better ideas on how this might work?

I'm going to see if I can hack something together in this feature branch.

https://github.com/siteorigin/siteorigin-panels/tree/feature/customizer-live-preview

**Comment by MatthewEppelsheimer** [comment]
@gregpriday that all sounds good to me except for the first half of the third step, where other customizer controls are cleared out. I would vote to add a "Page Builder" section to the Customizer that you can drill into for details, similar to how widgets normally work in the Customizer. And, I'd vote to have this accessible whether clicking "Live preview" or getting to the Customizer as normal. "Live preview" would essentially be a link to the Customizer. 

This would allow you to have the focused view of only Page Builder controls when you want them, while also allowing you to use the Customizer normally. 

I'm not sure then if step 2 would still be necessary. It may be necessary to add some some post meta to build the new customizer sections for, if there isn't some meta data already already available for that use.

**Comment by gregpriday** [comment]
I've done some experimenting on this and actually have a semi working implementation. It's a bit of a hack that creates a temporary sidebar for each cell in a Page Builder page and populates them with the widgets on the current page.

There are a few things I do and don't like about using the customizer as a "Live Editor". The first is that we are essentially hacking Page Builder into the customizer. More importantly though, it limits what we can do in the Live Editing mode. For example, in the current live editor, we could add a feature that allows users to perform full frontend editing.

So right now, I think this would be a nice addition to the Customizer but it isn't necessarily a good replacement for the Live Editor.

It is very fun to play with though.

![image](https://cloud.githubusercontent.com/assets/1126859/9625912/ef298c1e-5159-11e5-99e9-f63f4c2702b8.png)

**Comment by NickHeurter** [comment]
This seems like a really nice feature. It's something I've been thinking of since using the SiteOrigin Page Builder and your preview @gregpriday looks stunning! But your idea about creating a feature that allows users to perform full frontend editing sounds also very good! Keep on doing the good work!

**Comment by gregpriday** [comment]
So the Live Editor has improved quite a bit since I last tried to get it working in the customizer. Right now, I really prefer the idea of keeping the existing builder interface, rather than hacking Page Builder into the customizer.

The one thing would like to do in the future is add a builder interface into a custom field inside the customizer. Ultimately, I don't want to have to maintain 2 separate interfaces (the existing builder interface and a new Customizer interface). This would add a lot of overhead. 

Getting the builder working inside the Customizer though, would only be a 1-2 day task and it wouldn't require as much maintenance work.

**Comment by gregpriday** [comment]
We have started some work to further improve the Live Editor. The Customzier is great, but we're going to focus on making improvements to the Live Editor, rather than getting everything working in the Cusomizer.
