### ISSUE TITLE
Sidebars-Emulator Causes PHP Warning

### ISSUE THREAD

**Issue by MachineITSvcs** [siteorigin/siteorigin-panels#962]
I was receiving the following PHP error/warning:

`PHP message: PHP Warning:  Undefined array key 1 in /web/wp-content/plugins/siteorigin-panels/inc/sidebars-emulator.php on line 53`

I believe this is due to the preg_match not finding a match, and thus $num_match is not set a valid value. Considering that preg_match returns 0 on no match or false on failure, may I suggest that the lines 52 and 53 be updated to something like:

```
if(!empty(preg_match('/-([0-9]+$)/', $sidebar_id, $num_match))) {
    $args[0][ $num_match[1] ] = $widget_instance;
}
```

This will require the match to be found before attempting to set to what would otherwise be an undefined variable array value, similar to how you already check $opt_matches is not empty on line 33. Considering I also don't see the $args being set in the function, but passed as an argument, should there be logic beforehand that ensures $args[0] is set as well? Maybe something like:

`if(!isset($args[0])) $args[0] = array();`

Perhaps on line 30 (before the check for $opt_matches), and maybe move the "return $args[0];" line to the end of the function instead of before the last curly bracket "}" unless you don't want this function to return $args[0] when no $opt_matches found?

**Comment by AlexGStapleton** [comment]
Hi @MachineITSvcs,

Thank you for the report. I'm not too sure how `preg_match` could result in no results, but I absolutely can see the possibility of a notice if it did. There's really nothing we can do to emulate the widget if it does return nothing so not setting the id is the way to go. I've accounted for this possibility here: https://github.com/siteorigin/siteorigin-panels/pull/964

I've prepared a build of that PR for you to try, and you can [download it by clicking here](https://drive.google.com/uc?id=104Y5mU7gxrVpfOnssL8sQlqPiA4-O2Cb).

Before proceeding, do a backup.

Navigate to **Plugins > Installed Plugins** and deactivate Page Builder by SiteOrigin, and then delete it. Scroll to the top of the page and click Add New, Upload Plugin and upload siteorigin-panels.2.16.1-beta.zip. When prompted, activate Page Builder by SiteOrigin. Does this notice still occur for you?

> Considering I also don't see the $args being set in the function, but passed as an argument, should there be logic beforehand that ensures $args[0] is set as well?

It's safe to assume `$args[0]` will always exist if the sidebar emulator was called. It's set and provided by WordPress and it's been handed like that for over a decade so `$args[0]` will simply always exist.

> Perhaps on line 30 (before the check for $opt_matches), and maybe move the "return $args[0];" line to the end of the function instead of before the last curly bracket "}" unless you don't want this function to return $args[0] when no $opt_matches found?

This one I'm not 100% certain about. That area of the code was before my time so I'm unsure the reasoning for this but I can make an educated guess that it relates to widget filtering. If widget filtering is occurring, it's undesirable for `$args[0]` to be returned in this situation as it'll return in the widget being set when it otherwise wouldn't be. I can't be certain that's 100% the case but based on how it was written and a quick glance at the WordPress filtering functionality, that's likely the reasoning for why it was done like that.

Kind regards,
Alex
